
CREATE DATABASE EventosDB;
GO
USE EventosDB;

CREATE TABLE Users (
 Id INT IDENTITY PRIMARY KEY,
 Username NVARCHAR(100) UNIQUE NOT NULL,
 Password NVARCHAR(200) NOT NULL,
 IsAdmin BIT DEFAULT 0
);

CREATE TABLE Events (
 Id INT IDENTITY PRIMARY KEY,
 Title NVARCHAR(200),
 Description NVARCHAR(MAX),
 EventType NVARCHAR(100),
 Location NVARCHAR(200),
 StartDate DATETIME2,
 EndDate DATETIME2,
 CreatedByUserId INT
);
